version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Retrieving API Gateway URL from CloudFormation"
      - API_GATEWAY_URL=$(aws cloudformation describe-stacks \
          --stack-name your-stack-name \
          --query "Stacks[0].Outputs[?OutputKey=='ApiGatewayURL'].OutputValue" \
          --output text)
      - echo "API Gateway URL is $API_GATEWAY_URL"
      - export REACT_APP_API_URL=$API_GATEWAY_URL   # React expects environment variables to be prefixed with REACT_APP
  build:
    commands:
      - echo "Building the React app with API Gateway URL"
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)
